USE MagicCorp
GO

SELECT *
FROM SALGRADE

SELECT ENAME, GRADE
FROM EMPLOYEE, SALGRADE
WHERE LOWSAL <= SALARY AND SALARY <= HIGHSAL

SELECT ENAME, GRADE
FROM EMPLOYEE, SALGRADE
WHERE SALARY BETWEEN LOWSAL AND HIGHSAL

SELECT E.ENAME AS [EMPLOYEENAME], M.ENAME AS [MANAGERNAME]
FROM EMPLOYEE E, EMPLOYEE m
WHERE E.MANAGER = E.ENO

SELECT ENAME, GRADE, DNAME
FROM EMPLOYEE, SALGRADE, DEPARTMENT
WHERE SALARY BETWEEN LOWSAL AND HIGHSAL
AND EMPLOYEE.DNO = DEPARTMENT.DNO

SELECT ENAME, DNAME
FROM EMPLOYEE INNER JOIN DEPARTMENT ON EMPLOYEE.ENAME = DEPARTMENT.DNAME