USE MagicCorp
GO
SELECT AVG(SALARY) AS AVERAGE
FROM EMPLOYEE

SELECT MAX(SALARY) AS MAXIMUM, MIN(SALARY) AS MINIMUM
FROM EMPLOYEE

SELECT AVG(SALARY) AS AVERGE, VAR(SALARY) AS VARIATION, STDEV(SALARY) AS STD
FROM EMPLOYEE

SELECT COUNT(*) AS NUMROW, COUNT(COMMISSION) AS COMM
FROM EMPLOYEE

SELECT COUNT(JOB) as NUMJOB, COUNT(DISTINCT JOB) AS DIS_JOB
FROM EMPLOYEE

SELECT DNO, AVG(SALARY) AS DNOAVG
FROM EMPLOYEE
GROUP BY DNO

SELECT DNO, AVG(SALARY) AS DNOAVG
FROM EMPLOYEE
GROUP BY DNO
HAVING MAX(SALARY) > 500

SELECT DNO, JOB, SUM(SALARY) AS SUMSAL
FROM EMPLOYEE
GROUP BY DNO, JOB

SELECT DNO, JOB, SUM(SALARY) AS SUMSAL
FROM EMPLOYEE
GROUP BY DNO, JOB with rollup

SELECT DNO, JOB, SUM(SALARY) AS SUMSAL
FROM EMPLOYEE
GROUP BY DNO, JOB with cube

SELECT DNO, JOB, SUM(SALARY) AS SUMSAL
FROM EMPLOYEE
GROUP BY GROUPING SETS( (DNO), (JOB))