USE MagicCorp
GO
SELECT DNAME
FROM DEPARTMENT
WHERE DEPARTMENT.DNO = (SELECT DNO
						FROM EMPLOYEE
						WHERE EMPLOYEE.ENO = 103)

SELECT ENO, DNO
FROM EMPLOYEE
WHERE EMPLOYEE.SALARY > ANY (SELECT SALARY
							FROM EMPLOYEE
							WHERE DNO = 20)

SELECT ENO, DNO, SALARY
FROM EMPLOYEE 
WHERE EMPLOYEE.SALARY > ALL (SELECT SALARY FROM EMPLOYEE WHERE DNO = 10)

SELECT ENAME
FROM EMPLOYEE
WHERE EXISTS (SELECT * FROM EMPLOYEE WHERE SALARY + COMMISSION > 500)

SELECT ENO, ENAME, SALARY, DNO
FROM EMPLOYEE
WHERE DNO IN (SELECT DNO FROM EMPLOYEE WHERE DNO = 110)
AND SALARY IN (SELECT SALARY FROM EMPLOYEE WHERE DNO =100)

SELECT ENAME, ENO, SALARY, DNO
FROM EMPLOYEE E
WHERE DNO IN (SELECT DNO FROM EMPLOYEE M WHERE E.MANAGER = M.ENO)