USE MagicCorp
GO

SELECT DISTINCT DNO, FIRST_VALUE(SALARY) OVER(PARTITION BY DNO ORDER BY SALARY asc) as highest
FROM EMPLOYEE

SELECT DISTINCT ENO, SALARY, LAG(SALARY, 1) OVER(ORDER BY SALARY asc) as LAG_VALUE,
							LEAD(SALARY, 1) OVER(ORDER BY SALARY asc) as LEAD_VALUE
FROM EMPLOYEE