USE MagicCorp
GO
(SELECT * FROM EMPLOYEE WHERE DNO = 10)
UNION
(SELECT * FROM EMPLOYEE WHERE JOB = 'staff')

(SELECT * FROM EMPLOYEE WHERE DNO = 10)
INTERSECT
(SELECT * FROM EMPLOYEE WHERE JOB = 'staff')

(SELECT * FROM EMPLOYEE WHERE DNO = 10)
EXCEPT
(SELECT * FROM EMPLOYEE WHERE JOB = 'staff')

(SELECT * FROM EMPLOYEE WHERE DNO = 10)
UNION ALL
(SELECT * FROM EMPLOYEE WHERE JOB = 'staff')

(SELECT ENO, ENAME, NULL, DNO FROM EMPLOYEE)
UNION
(SELECT NULL, NULL, DNAME, DNO FROM DEPARTMENT)