USE MagicCorp
GO

SELECT ENAME, DNO 
FROM EMPLOYEE
WHERE ENO = 110

SELECT ENAME, SALARY * 12 AS YEARPAY 
FROM EMPLOYEE

SELECT ENAME, JOB 
FROM EMPLOYEE
WHERE DNO = 20 AND SALARY > 400

SELECT DISTINCT JOB
FROM EMPLOYEE

SELECT * 
FROM EMPLOYEE
WHERE SALARY BETWEEN 400 AND 700

SELECT ENAME, JOB 
FROM EMPLOYEE
WHERE JOB IN('section', 'senior')

SELECT * 
FROM EMPLOYEE
WHERE COMMISSION IS NULL

SELECT *
FROM EMPLOYEE
WHERE COMMISSION IS NOT NULL

SELECT DNAME, LOC
FROM DEPARTMENT
WHERE DNAME LIKE 'H%n'

SELECT ENAME, SALARY, DNO
FROM EMPLOYEE
WHERE COMMISSION IS NULL
ORDER BY SALARY DESC