USE MagicCorp
GO

SELECT TOP(20) PERCENT WITH TIES *
FROM EMPLOYEE
ORDER BY SALARY DESC

SELECT ENAME, SALARY, RANK() OVER(order by salary asc) as rank
FROM EMPLOYEE

SELECT ENAME, SALARY, DENSE_RANK() OVER(order by salary asc) as rank
FROM EMPLOYEE

SELECT ENAME, SALARY, ROW_NUMBER() OVER(order by salary asc) as rank
FROM EMPLOYEE

SELECT ENAME, SALARY, NTILE(5) OVER(order by salary asc) as rank
FROM EMPLOYEE