USE MagicCorp
GO

SELECT DNAME, AVG_SAL
FROM (SELECT DNO, AVG(SALARY) as AVG_SAL
		FROM EMPLOYEE
		GROUP BY DNO) AS S, DEPARTMENT D
WHERE S.DNO = D.DNO

WITH S(DNO, AVG_SAL)
AS (SELECT DNO, AVG(SALARY)
	FROM EMPLOYEE
	GROUP BY DNO)
SELECT DNAME, AVG_SAL
FROM S, DEPARTMENT D
WHERE S.DNO = D.DNO
